In [32]:
import os 
import pandas as pd
import os

BASE_DIR = os.path.dirname(os.getcwd())
RAW_DATA = os.path.join(BASE_DIR, "data", "raw")

In [33]:
print("==============================================")
print("     INSPECTING FILE 1: Fund Master")
print("==============================================")
df = pd.read_csv(os.path.join(RAW_DATA, "01_fund_master.csv"))


print("--- SHAPE ---")
print(df.shape)


print("\n--- DTYPES ---")
print(df.dtypes)


print("\n--- HEAD ---")
df.head()

==============================================
     INSPECTING FILE 1: Fund Master
==============================================
--- SHAPE ---
(40, 15)

--- DTYPES ---
amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

--- HEAD ---

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [34]:
print("==============================================")
print("     INSPECTING FILE 2: Nav History")
print("==============================================")
df2 = pd.read_csv(os.path.join(RAW_DATA, "02_nav_history.csv"))


print("--- SHAPE ---")
print(df2.shape)


print("\n--- DTYPES ---")
print(df2.dtypes)


print("\n--- HEAD ---")
df2.head()

==============================================
     INSPECTING FILE 2: Nav History
==============================================
--- SHAPE ---
(46000, 3)

--- DTYPES ---
amfi_code      int64
date             str
nav          float64
dtype: object

--- HEAD ---

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [35]:
print("==============================================")
print("     INSPECTING FILE 3: Aum By Fund House ")
print("==============================================")
df3 = pd.read_csv(os.path.join(RAW_DATA, "03_aum_by_fund_house.csv"))


print("--- SHAPE ---")
print(df3.shape)


print("\n--- DTYPES ---")
print(df3.dtypes)


print("\n--- HEAD ---")
df3.head()

==============================================
     INSPECTING FILE 3: Aum By Fund House
==============================================
--- SHAPE ---
(90, 5)

--- DTYPES ---
date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

--- HEAD ---

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [36]:
print("==============================================")
print("     INSPECTING FILE 4: Monthly Sip Inflows ")
print("==============================================")
df4 = pd.read_csv(os.path.join(RAW_DATA, "04_monthly_sip_inflows.csv"))


print("--- SHAPE ---")
print(df4.shape)


print("\n--- DTYPES ---")
print(df4.dtypes)


print("\n--- HEAD ---")
df4.head()

==============================================
     INSPECTING FILE 4: Monthly Sip Inflows
==============================================
--- SHAPE ---
(48, 6)

--- DTYPES ---
month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

--- HEAD ---

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [37]:
print("==============================================")
print("     INSPECTING FILE 5: Category Inflows ")
print("==============================================")
df5 = pd.read_csv(os.path.join(RAW_DATA, "05_category_average_returns.csv"))


print("--- SHAPE ---")
print(df5.shape)


print("\n--- DTYPES ---")
print(df5.dtypes)


print("\n--- HEAD ---")
df5.head()

==============================================
     INSPECTING FILE 5: Category Inflows
==============================================

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\laksh\\OneDrive\\Documents\\GitHub\\Capstone_Project_Mutual_Fund_Analytics\\data\\raw\\05_category_average_returns.csv'

In [ ]:
print("==============================================")
print("     INSPECTING FILE 6: Industry Folio Count ")
print("==============================================")
df6 = pd.read_csv(os.path.join(RAW_DATA, "06_expense_ratio.csv"))


print("--- SHAPE ---")
print(df6.shape)


print("\n--- DTYPES ---")
print(df6.dtypes)


print("\n--- HEAD ---")
df6.head()

==============================================
     INSPECTING FILE 6: Industry Folio Count
==============================================
--- SHAPE ---
(21, 6)

--- DTYPES ---
month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

--- HEAD ---

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [ ]:
print("==============================================")
print("     INSPECTING FILE 7: Scheme Performance ")
print("==============================================")
df7 = pd.read_csv(os.path.join(RAW_DATA, "07_risk_metrics.csv"))


print("--- SHAPE ---")
print(df7.shape)


print("\n--- DTYPES ---")
print(df7.dtypes)


print("\n--- HEAD ---")
df7.head()

==============================================
     INSPECTING FILE 7: Scheme Performance
==============================================
--- SHAPE ---
(40, 19)

--- DTYPES ---
amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

--- HEAD ---

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [ ]:
print("==============================================")
print("     INSPECTING FILE 8: Investor Transactions ")
print("==============================================")
df8 = pd.read_csv(os.path.join(RAW_DATA, "08_fund_manager.csv"))


print("--- SHAPE ---")
print(df8.shape)


print("\n--- DTYPES ---")
print(df8.dtypes)


print("\n--- HEAD ---")
df8.head()

==============================================
     INSPECTING FILE 8: Investor Transactions
==============================================
--- SHAPE ---
(32778, 13)

--- DTYPES ---
investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

--- HEAD ---

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [ ]:
print("==============================================")
print("     INSPECTING FILE 9: Portfolio Holdings ")
print("==============================================")
df9 = pd.read_csv(os.path.join(RAW_DATA, "09_portfolio_holdings.csv"))


print("--- SHAPE ---")
print(df9.shape)


print("\n--- DTYPES ---")
print(df9.dtypes)


print("\n--- HEAD ---")
df9.head()

==============================================
     INSPECTING FILE 9: Portfolio Holdings
==============================================
--- SHAPE ---
(322, 8)

--- DTYPES ---
amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

--- HEAD ---

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [ ]:
print("==============================================")
print("     INSPECTING FILE 10: Benchmark Indice ")
print("==============================================")
df10 = pd.read_csv(os.path.join(RAW_DATA, "10_benchmark_indices.csv"))


print("--- SHAPE ---")
print(df10.shape)


print("\n--- DTYPES ---")
print(df10.dtypes)


print("\n--- HEAD ---")
df10.head()

==============================================
     INSPECTING FILE 10: Benchmark Indice
==============================================
--- SHAPE ---
(8050, 3)

--- DTYPES ---
date               str
index_name         str
close_value    float64
dtype: object

--- HEAD ---

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [ ]:
df = pd.read_csv(os.path.join(RAW_DATA, "01_fund_master.csv"))
print(df.columns)

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

In [ ]:
print(df['fund_house'].unique())

<StringArray>
[         'SBI Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',          'Nippon India MF',
        'Kotak Mahindra MF',         'Axis Mutual Fund',
 'Aditya Birla Sun Life MF',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str

In [ ]:
print(df['category'].unique())

<StringArray>
['Equity', 'Debt']
Length: 2, dtype: str

In [ ]:
print(df['sub_category'].unique())

<StringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str

In [ ]:
print(df['risk_category'].unique())

<StringArray>
['Moderate', 'Very High', 'Low', 'High', 'Moderately High']
Length: 5, dtype: str

In [ ]:
print(df['amfi_code'].unique())

[119551 119552 119598 119599 119120 100016 125497 100033 125498 100025
 120503 120504 120505 120506 120507 118632 118633 118634 118635 118636
 120841 120842 120843 120844 119092 119093 119094 119095 101206 101207
 101208 102885 102886 102887 148567 148568 148569 149322 149323 149324]

In [ ]:
df1 = pd.read_csv(os.path.join(RAW_DATA, "02_nav_history.csv"))

fund_master_codes = set(df['amfi_code'])
nav_history_codes = set(df1['amfi_code'])

if fund_master_codes.issubset(nav_history_codes):
    print("Yes, every AMFI code in fund_master exists in nav_history.")
else:
    print("No, some AMFI codes are missing.")

Yes, every AMFI code in fund_master exists in nav_history.

In [ ]:
import pandas as pd
import os

path = RAW_DATA

for file in os.listdir(path):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(path, file))

        print(f"\n{'='*50}")
        print(f"File: {file}")
        
        print(f"Missing Values:{df.isnull().sum().sum()}")
        print(f"Duplicate Rows: {df.duplicated().sum()}")

==================================================
File: 01_fund_master.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: 02_nav_history.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: 03_aum_by_fund_house.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: 04_monthly_sip_inflows.csv
Missing Values:12
Duplicate Rows: 0

==================================================
File: 05_category_inflows.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: 06_industry_folio_count.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: 07_scheme_performance.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: 08_investor_transactions.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: 09_portfolio_holdings.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: 10_benchmark_indice.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: axis_bluechip.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: hdfc_top_100.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: icici_bluechip.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: kotak_bluechip.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: nippon_large_cap.csv
Missing Values:0
Duplicate Rows: 0

==================================================
File: sbi_bluechip.csv
Missing Values:0
Duplicate Rows: 0

In [38]:
df = pd.read_csv(os.path.join(RAW_DATA, "04_monthly_sip_inflows.csv"))
df.isnull().sum()

month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

# Data Quality Summary

## Overview

An initial data quality assessment was performed on the mutual fund datasets provided for the project.

## Observations

* All datasets were successfully loaded into Pandas DataFrames without any errors.
* Dataset dimensions and data types were inspected using `.shape` and `.dtypes`.
* Unique fund houses, categories, sub-categories, and risk categories were successfully identified.
* The `amfi_code` column was found to be present and can be used as a unique identifier for mutual fund schemes.
* AMFI codes from `fund_master` were validated against `nav_history` to ensure consistency across datasets.
* No duplicate records were found in the datasets examined during the initial exploration.
* The `04_monthly_sip_inflows.csv` dataset contains 12 missing values in the `yoy_growth_pct` column.
* These missing values are likely due to insufficient previous-year data required for calculating year-over-year growth percentages.
* Apart from the above missing values, no major data quality issues or inconsistencies were observed.
* Overall, the datasets appear suitable for further analysis and dashboard development.

## Conclusion

The overall quality of the data is good. Minor missing values were identified in the `yoy_growth_pct` column; however, the datasets are largely consistent and ready for subsequent stages such as data cleaning, transformation, exploratory data analysis, and visualization.